# Generated by Django 5.2.6 on 2026-05-08 05:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='car_DB',
            fields=[
                ('car_name', models.CharField(max_length=18)),
                ('engine_no', models.IntegerField(primary_key='card_ID', serialize=False)),
                ('company', models.CharField(max_length=18)),
                ('fuel_capacity', models.FloatField()),
                ('color', models.CharField(max_length=18)),
            ],
        ),
    ]
