# Generated by Django 5.2.6 on 2026-05-14 13:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ormapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Food_ordering',
            fields=[
                ('hotel_name', models.CharField(max_length=18)),
                ('no_of_quantity', models.IntegerField(primary_key='card_ID', serialize=False)),
                ('food_name', models.CharField(max_length=18)),
                ('Food_rating', models.FloatField()),
                ('Description', models.CharField(max_length=18)),
            ],
        ),
        migrations.DeleteModel(
            name='car_DB',
        ),
    ]
